server:
  port: 10086

spring:
  profiles: Eureka
  application: 
    name: Eureka-10086

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
---
server:
  port: 8081

spring:
  profiles: test

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
  
