server:
  port: 10086

spring:
  profiles: Eureka
  application:
    name: Eureka-10086

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    register-with-eureka: false   #不注册自己
    fetch-registry: false   #自己为注册中心
---

  
